default:
  image: ${F5_CI_IMAGE}

stages:
  - lint

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends shellcheck

lint:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  stage: lint
  script:
    - ./lint.sh
