default:
  image: alpine:latest

stages:
  - lint

before_script:
  - apk update
  - apk add bash shellcheck

lint:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  stage: lint
  script:
    - ./lint.sh
