# SPDX-License-Identifier: GPL-3.0-or-later
# (c) Axians IT Security GmbH
# Jürgen Mang <juergen.mang@sec.axians.de>
# https://www.axians.de/security
# https://github.com/AxiansITSecurity/Restsh

default:
  image: ${F5_CI_IMAGE}

stages:
  - lint
  - test_restsh

lint_job:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  tags:
    - ${F5_ENV}_lint
  stage: lint
  script:
    - ./lint.sh

test_restsh_job:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  tags:
    - ${F5_ENV}_lint
  stage: test_restsh
  script:
    - ./test/test.sh -g restsh
