#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# restsh (c) 2023 Juergen Mang <juergen.mang@axians.de>
# https://github.com/JuergenMang/restsh

# Shortdesc: Central http functions for all common REST methods.
# Desc:
# Central http functions for all common REST methods.

# Strict errorhandling
set -uo pipefail

# Debug mode
[ -n "${RESTSH_DEBUG+x}" ] && set -x

# Generic http request function
restsh.http() {
    local BODY=0
    local RAW=0
    local OPTION OPTIND
    while getopts ':br' OPTION
    do
        case "$OPTION" in
            b) BODY=1 ;;
            r) RAW=1 ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ -z "${2+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: restsh.http [-b] [-r] <method> <uri>"
        echo -e "\tUse -b for a body and pipe the payload in the command."
        echo -e "\tUse -r for raw output."
        return 1
    fi
    local METHOD=$1
    local URI=$2

    # We must set the curl options first
    restsh.utility.setcurloptions

    if [ "$BODY" -eq 1 ]
    then
        # Read body from STDIN
        RESTSH_CURL_OPTS+=("-d" "@-")
        # Add header
        RESTSH_CURL_OPTS+=("-H" "Content-Type: $RESTSH_CONTENT")
    fi

    if ! OUTPUT=$($RESTSH_CURL_BIN "${RESTSH_CURL_OPTS[@]}" -X "$METHOD" "${RESTSH_URL}${URI}")
    then
        echo_err "$METHOD ${RESTSH_URL}${URI} failed"
        echo_err "$OUTPUT"
        unset RESTSH_CURL_OPTS
        return 1
    fi
    unset RESTSH_CURL_OPTS
    if [ "$RAW" -eq 1 ]
    then
        echo "$OUTPUT"
    else
        restsh.utility.parseoutput "$OUTPUT"
    fi
    return 0
}

# Issues a DELETE request
DELETE() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':r' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: DELETE [-r] <uri>"
        echo -e "\tUse -r for raw output."
        return 1
    fi
    restsh.http "${ARGS[@]}" DELETE "$1"
}

# Issues a GET request
GET() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':r' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: GET [-r] <uri>"
        echo -e "\tUse -r for raw output."
        return 1
    fi
    restsh.http "${ARGS[@]}" GET "$1"
}

# Issues a PATCH request
PATCH() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':r' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: PATCH [-r] <uri>"
        echo -e "\tPipe the payload in the command."
        echo -e "\tUse -r for raw output."
        return 1
    fi
    restsh.http "${ARGS[@]}" PATCH "$1"
}

# Issues a POST request
POST() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':r' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: POST [-r] <uri>"
        echo -e "\tPipe the payload in the command."
        echo -e "\tUse -r for raw output."
        return 1
    fi
    restsh.http "${ARGS[@]}" POST "$1"
}

# Issues a PUT request
PUT() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':r' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            *) OPTION="invalid" ;;
        esac
    done
    shift "$(($OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: PUT [-r] <uri>"
        echo -e "\tPipe the payload in the command."
        echo -e "\tUse -r for raw output."
        return 1
    fi
    restsh.http "${ARGS[@]}" PUT "$1"
}

export -f restsh.http
export -f DELETE
export -f GET
export -f PATCH
export -f POST
export -f PUT
