#!/usr/bin/env bash

# Author: Juergen Mang <juergen.mang@axians.de>
# Date: 2024-06-27

# Shortdesc: Central http functions for all common REST methods.
# Desc:
# Central http functions for all common REST methods.

# Strict error handling
set -uo pipefail

# Debug mode
[ -n "${RESTSH_DEBUG+x}" ] && set -x

# Generic http request function
restsh.http() {
    local BODY=0
    local RAW=0
    local RETRIES=0
    local OUTPUT_FILE=""
    local OPTION OPTIND
    while getopts ':brc:o:' OPTION
    do
        case "$OPTION" in
            b) BODY=1 ;;
            r) RAW=1 ;;
            c) RETRIES="$OPTARG" ;;
            o) OUTPUT_FILE="$OPTARG" ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ -z "${2+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: restsh.http [-b] [-r] <method> <uri>" 1>&2
        echo -e "\tUse -b for a body and pipe the payload in the command." 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries" 1>&2
        echo -e "\tUse -o to define an output file" 1>&2
        return 1
    fi
    local METHOD=$1
    local URI=$2

    # We must set the curl options first
    restsh.util.setcurloptions

    if [ "$BODY" -eq 1 ]
    then
        # Read body from STDIN
        RESTSH_CURL_OPTS+=("-d" "@-")
        # Add header
        RESTSH_CURL_OPTS+=("-H" "Content-Type: $RESTSH_CONTENT")
    fi

    if [ "$RETRIES" -gt 0 ]
    then
        RESTSH_CURL_OPTS+=("--retry" "$RETRIES" "--retry-all-errors" --retry-delay "10")
    fi

    if [ -n "$OUTPUT_FILE" ]
    then
        RESTSH_CURL_OPTS+=("-o" "$OUTPUT_FILE")
    fi

    local ERROR_TMP
    ERROR_TMP=$(mktemp)
    if ! OUTPUT=$($RESTSH_CURL_BIN "${RESTSH_CURL_OPTS[@]}" -X "$METHOD" "${RESTSH_URL}${URI}" 2>"$ERROR_TMP")
    then
        local ERROR
        ERROR=$(<"$ERROR_TMP")
        rm -f "$ERROR_TMP"
        print_json_err_curl "$ERROR" "$OUTPUT" "$METHOD ${RESTSH_URL}${URI}"
        unset RESTSH_CURL_OPTS
        return 1
    fi
    rm -f "$ERROR_TMP"
    unset RESTSH_CURL_OPTS
    if [ "$RAW" -eq 1 ]
    then
        echo "$OUTPUT"
    else
        restsh.util.parseoutput "$OUTPUT"
    fi
    return 0
}

# Download a file in chunks (default 512kB).
restsh.download() {
    if [ -z "${1+x}" ] || [ -z "${2+x}" ] || [ -z "${3+x}" ]
    then
        echo "Download a file in chunks of ${CHUNK_SIZE} bytes." 1>&2
        echo "Usage: restsh.download <uri> <size> <filename>" 1>&2
        echo "Use 0 for <size> to enable auto-detection of the size." 1>&2
        return 1
    fi
    local URI=$1
    local TOTAL_SIZE=$2
    local FILENAME=$3

    # We must set the curl options first
    restsh.util.setcurloptions

    # Remove local file
    rm -f "${FILENAME}"

    local ERROR_TMP
    ERROR_TMP=$(mktemp)

    # Get file size if not specified
    if [ "$TOTAL_SIZE" -eq 0 ]
    then
        TOTAL_SIZE=$($RESTSH_CURL_BIN \
            -H "Connection: close" \
            -H "Content-Range: 0-1/*" \
            -i "${RESTSH_CURL_OPTS[@]}" "${RESTSH_URL}${URI}" 2>"$ERROR_TMP" \
            | awk -F/ '/Content-Range/ {print $2}' | tr -d '\r')
        # Check if TOTAL_SIZE is gt 0
        if [ "$TOTAL_SIZE" = "*" ] || [ "$TOTAL_SIZE" -le 0 ]
        then
            local ERROR
            ERROR=$(<"$ERROR_TMP")
            rm -f "$ERROR_TMP"
            print_json_err_curl "Could not determine download size" "$ERROR" "GET ${RESTSH_URL}${URI}"
            unset RESTSH_CURL_OPTS
            return 1
        fi
        #echo "Download size is $TOTAL_SIZE"
    fi

    # Download file in chunks, range header is zero-indexed
    # and includes range start and end.
    RANGE_END=$((TOTAL_SIZE-1))
    local START=0
    local END=0
    local CHUNK_SIZE=$RESTSH_CHUNK_SIZE
    [ "$TOTAL_SIZE" -lt "$CHUNK_SIZE" ] && CHUNK_SIZE=$TOTAL_SIZE

    # Initialize Connection type at Keep-Alive
    local CONNECTION="Keep-Alive"

    while [ "$END" -lt "$RANGE_END" ]
    do
        END=$((START+CHUNK_SIZE-1))
        if [ "$END" -gt "$RANGE_END" ]
        then
            END=$RANGE_END
            CONNECTION="Close"
        fi
        local CONTENT_RANGE="${START}-${END}/${TOTAL_SIZE}"
        #echo "$CONTENT_RANGE"
        if ! $RESTSH_CURL_BIN \
            -H "Content-Range: $CONTENT_RANGE" \
            -H "Connection: $CONNECTION" \
            "${RESTSH_CURL_OPTS[@]}" "${RESTSH_URL}${URI}" \
            >> "${FILENAME}" 2>"$ERROR_TMP"
        then
            local ERROR
            ERROR=$(<"$ERROR_TMP")
            rm -f "$ERROR_TMP"
            print_json_err_curl "Download failed" "$ERROR" "GET ${RESTSH_URL}${URI}"
            unset RESTSH_CURL_OPTS
            return 1
        fi
        # Do not calculate the new range start, we do not know if we got really the requested chunk length
        # We use the file size written to disk as range start
        START=$(restsh.util.filesize "$FILENAME")
    done
    rm -f "$ERROR_TMP"
    unset RESTSH_CURL_OPTS
    print_json_ok_curl "Successful" "GET ${RESTSH_URL}${URI}"
    return 0
}

# Uploads a file in chunks (default 512kB).
restsh.upload() {
    if [ -z "${1+x}" ] || [ -z "${2+x}" ]
    then
        echo "Upload a file in chunks of ${CHUNK_SIZE} bytes." 1>&2
        echo "Usage: restsh.upload <uri> <filename>" 1>&2
        return 1
    fi
    local URI=$1
    local FILENAME=$2
    local TOTAL_SIZE
    if ! TOTAL_SIZE=$(restsh.util.filesize "$FILENAME")
    then
        print_json_err "File '$FILENAME' not found."
        return 1
    fi

    # We must set the curl options first
    restsh.util.setcurloptions

    # Upload file in chunks, range header is zero-indexed
    # and includes range start and end.
    RANGE_END=$((TOTAL_SIZE-1))
    local START=0
    local END=0
    local CHUNK_SIZE=$RESTSH_CHUNK_SIZE
    [ "$TOTAL_SIZE" -lt "$CHUNK_SIZE" ] && CHUNK_SIZE=$TOTAL_SIZE

    # Initialize Connection type at Keep-Alive
    local CONNECTION="Keep-Alive"

    local ERROR_TMP
    ERROR_TMP=$(mktemp)
    SKIP=0
    while [ "$END" -lt "$RANGE_END" ]
    do
        END=$((START+CHUNK_SIZE-1))
        if [ "$END" -gt "$RANGE_END" ]
        then
            END=$RANGE_END
            CONNECTION="Close"
        fi
        local CONTENT_RANGE="${START}-${END}/${TOTAL_SIZE}"
        #echo "$CONTENT_RANGE"
        if ! OUTPUT=$(dd status=none if="$FILENAME" count=1 skip="$SKIP" bs="$CHUNK_SIZE" \
            | $RESTSH_CURL_BIN \
                -H "Content-Range: $CONTENT_RANGE" \
                -H "Content-Type: application/octet-stream" \
                -H "Connection: $CONNECTION" \
                "${RESTSH_CURL_OPTS[@]}" "${RESTSH_URL}${URI}" \
                --data-binary @- 2>"$ERROR_TMP")
        then
            local ERROR
            ERROR=$(<"$ERROR_TMP")
            rm -f "$ERROR_TMP"
            print_json_err_curl "Upload failed" "$ERROR" "POST ${RESTSH_URL}${URI}"
            unset RESTSH_CURL_OPTS
            return 1
        fi
        START=$((END+1))
        SKIP=$((SKIP+1))
    done
    rm -f "$ERROR_TMP"
    unset RESTSH_CURL_OPTS
    print_json_ok_curl "Successful" "POST ${RESTSH_URL}${URI}"
    return 0
}

# Issues a DELETE request
DELETE() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: DELETE [-r] [-c] <uri>" 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("DELETE" "$1")
    restsh.http "${ARGS[@]}"
}

# Downloads a file
DOWNLOAD() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':c:' OPTION
    do
        case "$OPTION" in
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ -z "${2+x}" ]  || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: DOWNLOAD [-r] [-c] <uri> <output filename>" 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    local URI=$1
    local OUT="$2"
    ARGS+=("-o" "$OUT" "GET" "$URI")
    if restsh.http "${ARGS[@]}"
    then
        [ ! -s "$OUT" ] && return 1
        return 0
    fi
    return 1
}

# Issues a GET request
GET() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: GET [-r] [-c] <uri>" 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("GET" "$1")
    restsh.http "${ARGS[@]}"
}

# Issues a GET request
OPTIONS() {
    local ARGS=()
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: OPTIONS [-r] [-c] <uri>" 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("OPTIONS" "$1")
    restsh.http "${ARGS[@]}"
}

# Issues a PATCH request
PATCH() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: PATCH [-r] [-c] <uri>" 1>&2
        echo -e "\tPipe the payload in the command." 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("PATCH" "$1")
    restsh.http "${ARGS[@]}"
}

# Issues a POST request
POST() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: POST [-r] [-c] <uri>" 1>&2
        echo -e "\tPipe the payload in the command." 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("POST" "$1")
    restsh.http "${ARGS[@]}"
}

# Issues a PUT request
PUT() {
    local ARGS=("-b")
    local OPTION OPTIND
    while getopts ':rc:' OPTION
    do
        case "$OPTION" in
            r) ARGS+=("-r") ;;
            c) ARGS+=("-c" "$OPTARG") ;;
            *) OPTION="invalid"; break ;;
        esac
    done
    shift "$((OPTIND -1))"
    if [ -z "${1+x}" ] || [ "$OPTION" == "invalid" ]
    then
        echo "Usage: PUT [-r] [-c] <uri>" 1>&2
        echo -e "\tPipe the payload in the command." 1>&2
        echo -e "\tUse -r for raw output." 1>&2
        echo -e "\tUse -c to define retries." 1>&2
        return 1
    fi
    ARGS+=("PUT" "$1")
    restsh.http "${ARGS[@]}"
}

export -f restsh.http
export -f restsh.download
export -f restsh.upload
export -f DELETE
export -f DOWNLOAD
export -f GET
export -f OPTIONS
export -f PATCH
export -f POST
export -f PUT
