#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# restsh (c) 2023 Juergen Mang <juergen.mang@axians.de>
# https://github.com/JuergenMang/restsh

# Shortdesc: Provides some helper functions for mustache.
# Desc:
# Provides some helper functions for mustache.

# Writes a comma if it is not the first item in a loop.
COMMA_IF_NOT_FIRST() {
    [[ "${moCurrent#*.}" != "0" ]] && echo ","
}
