#!/usr/bin/env bash

# Author: Juergen Mang <juergen.mang@axians.de>
# Date: 2024-07-02

# Shortdesc: Sets environment variables for F5 Next.
# Desc:
# Sets environment variables for F5 Next.

# Strict error handling
set -uo pipefail

# Debug mode
[ -n "${RESTSH_DEBUG+x}" ] && set -x

[ -n "${NEXT_TASK_CHECK_INTERVAL+x}" ] || export NEXT_TASK_CHECK_INTERVAL=2
[ -n "${NEXT_TASK_TIMEOUT+x}" ] || export NEXT_TASK_TIMEOUT=18
