#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# restsh (c) 2023 Juergen Mang <juergen.mang@axians.de>
# https://github.com/JuergenMang/restsh

# Shortdesc: Some helper functions for mustache.
# Desc:
# Some helper functions for mustache.

# Returns a comma if it is not the first item in a loop.
MO_COMMA_IF_NOT_FIRST() {
    #shellcheck disable=SC2154
    [[ "${moCurrent#*.}" != "0" ]] && echo ","
}

# Returns a comma if arguments are not empty
MO_COMMA_IF_NOT_EMPTY() {
    local ARG_COUNT=${#MO_FUNCTION_ARGS[@]}
    local MAX_ARG_INDEX=$((ARG_COUNT-1))

    local BEFORE_VALUES=""
    # Join arguments but last
    local COUNT=0
    for ARG in ${MO_FUNCTION_ARGS}
    do
        BEFORE_VALUES="${BEFORE_VALUES}$(moShow "${ARG}" "${ARG}")"
        COUNT=$((COUNT+1))
        # Exit loop before last
        [ $COUNT -eq $MAX_ARG_INDEX ] && break
    done
    # Get last argument
    local LAST_VALUE
    LAST_VALUE=$(moShow "${MO_FUNCTION_ARGS[$MAX_ARG_INDEX]}" "${MO_FUNCTION_ARGS[$MAX_ARG_INDEX]}")
    if [ -n "$BEFORE_VALUES" ] && [ -n "$LAST_VALUE" ]
    then
        printf ","
    fi
}

# Returns the first entry from a comma separated list
MO_FIRST_COMMA_ENTRY() {
    local VALUE
    VALUE=$(moShow "$moCurrent" "$moCurrent")
    echo "${VALUE%%,*}"
}

# Returns the last entry from a comma separated list
MO_LAST_COMMA_ENTRY() {
    local VALUE
    VALUE=$(moShow "$moCurrent" "$moCurrent")
    echo "${VALUE#*,}"
}

# Returns an entry from a comma separated list
MO_GET_COMMA_ENTRY() {
    local VALUE
    VALUE=$(moShow "$moCurrent" "$moCurrent")
    local NR=$MO_FUNCTION_ARGS
    local CSV
    mapfile -t -d, <<< "$VALUE" CSV
    echo "${CSV[$NR]}"
}

# Includes a file base64 encoded
# Returns an unquoted string
MO_INCLUDE_BASE64() {
    base64 < "${MO_FUNCTION_ARGS[0]}" | tr -d '\n'
}

# Include an external template
MO_INCLUDE_PLAIN() {
    cat "${MO_FUNCTION_ARGS[0]}"
}

# Include a file json encoded
# Returns a quoted string
MO_INCLUDE_JSON_ENCODE() {
    jq "@json" "${MO_FUNCTION_ARGS[0]}"
}
